# Default values for vpa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

updater:
  # Command line arguments for the updater - descriptions and default values directly taken from:
  # https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/updater/main.go
  updaterInterval: 1m # Duration: How often updater should run; see https://pkg.go.dev/time#ParseDuration for valid formats.
  minReplicas: 2 # Integer: Minimum number of replicas to perform update.
  evictionTolerance: 0.5 # Float64: Fraction of replica count that can be evicted for update, if more than one pod can be evicted.
  evictionRateLimit: -1 # Float64: Number of pods that can be evicted per seconds. A rate limit set to 0 or -1 will disable the rate limiter.
  evictionRateBurst: 1 # Integer: Burst of pods that can be evicted.
  useAdmissionControllerStatus: true # Boolean: If true, updater will only evict pods when admission controller status is valid.
  vpaObjectNamespace: "" # String: Namespace to search for VPA objects. Empty means all namespaces will be used.
