# Default values for vpa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# NOTE: Since this is a very early version of the chart,
# it currently does not have any variables.