# COPYRIGHT NOTICE: This file has been copied without modifications
# directly from https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/deploy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-updater
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-updater
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-updater
  template:
    metadata:
      labels:
        app: vpa-updater
    spec:
      serviceAccountName: vpa-updater
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
        - name: updater
          image: k8s.gcr.io/autoscaling/vpa-updater:0.9.2
          imagePullPolicy: Always
          command:
            - "/updater" # Taken from Docker image
            - "--v=4" # Taken from Docker image
            - "--stderrthreshold=info" # Taken from Docker image
            - "-updater-interval={{.Values.updater.updaterInterval}}"
            - "-min-replicas={{.Values.updater.minReplicas}}"
            - "-eviction-tolerance={{.Values.updater.evictionTolerance}}"
            - "-eviction-rate-limit={{.Values.updater.evictionRateLimit}}"
            - "-eviction-rate-burst={{.Values.updater.evictionRateBurst}}"
            - "-kube-api-qps={{.Values.updater.kubeApiQps}}"
            - "-kube-api-burst={{.Values.updater.kubeApiBurst}}"
            - "-use-admission-controller-status={{.Values.updater.useAdmissionControllerStatus}}"
            - "-vpa-object-namespace={{.Values.updater.vpaObjectNamespace}}"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 200m
              memory: 1000Mi
            requests:
              cpu: 50m
              memory: 500Mi
          ports:
            - name: prometheus
              containerPort: 8943
