name: Test, Package, Publish
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: install minikube
        run: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && mv minikube-linux-amd64 /usr/local/bin/minikube && chmod +x /usr/local/bin/minikube
      - name: start minikube
        run: minikube start
      - name: install helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: checkout
        uses: actions/checkout@v2
      - name: helm install vpa
        run: helm install -n kube-system vpa ./vpa
  package:
    needs: test
    runs-on: ubuntu-latest
    name: Package
    steps:
      - name: install helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: checkout
        uses: actions/checkout@v2
      - name: helm package vpa
        run: helm package ./vpa
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: helm-package
          retention-days: 1
          path: |
            vpa-*.tgz
  publish:
    needs: package
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - name: install helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: refs/heads/gh-pages
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: helm-package
      - name: move artifiact into place and generate index
        run: mkdir -p ./helm-charts; mv -f vpa-*.tgz helm-charts/ && helm repo index ./helm-charts
      - name: set git user config
        run: git config --global user.email "workflow@github-actions.local" && git config --global user.name "GitHub Actions Workflow"
      - name: commit and push
        run: git add helm-charts/* && git commit -m "publish release" && git push
