name: Test, Package, Publish
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - name: install minikube
      run: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && mv minikube-linux-amd64 /usr/local/bin/minikube && chmod +x /usr/local/bin/minikube
    - name: start minikube
      run: minikube start